platform :ios, '7.0'
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.2'
pod 'AWSiOSSDK', '~> 1.7'
pod 'CountryPicker', :git => 'https://github.com/hollerbackco/CountryPicker.git'
pod 'CocoaLumberjack', '~> 1.8'
pod 'FMDB', '~> 2.3'
pod 'FontAwesomeKit/FontAwesome', '2.1.1'
pod 'FontAwesomeKit/IonIcons', '2.1.1'
pod 'FlurrySDK', '~> 4.4'
pod 'libPhoneNumber-iOS', '0.7.1'
pod 'Mantle', '1.3.1'
pod 'MHPrettyDate', '~> 1.1'
pod 'OHActionSheet', '~> 1.0'
pod 'KeenClient', '~> 3.2'
pod 'Reachability', '3.1.1'
pod 'ReactiveCocoa', '~> 2.3'
pod 'RHAddressBook', '~> 1.1'
pod 'SDWebImage', '3.6'
pod 'SWFSemanticVersion', '0.2'
pod 'JDStatusBarNotification', '~> 1.4'

